language: node_js

node_js:
  - "12"

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: gh_pages
  local_dir: dist/client
  on:
    branch: master
